// src/sections/BfsgSection.svelte
<script type="ts">
    import {INewPayoutRequestData, type IStudentBody} from "../Interfaces";
    import AngleIndicator from "../icons/AngleIndicator.svelte";
    import PayoutRequestsTable from "../components/PayoutRequestsTable.svelte";
    import BfsgRequestModal from "../components/BfsgRequestModal.svelte";
    import VorankuendigungRequestModal from "../components/VorankuendigungRequestModal.svelte";
    import {loggedInUser} from "../stores";

    export let studentBody: IStudentBody;
    export let bfsgPayoutRequests: INewPayoutRequestData[] | undefined;
    export let vorankuendigungPayoutRequests: INewPayoutRequestData[] | undefined;
    export let budgetTitlesBfsg: { [semester: string]: string };
    let opened: boolean = false;
    let bfsgModal: boolean = false;
    let vorankuendigungModal: boolean = false;

    const showBfsgModal = (e) => {
        bfsgModal = true;
        vorankuendigungModal = false;
    }

    const showVorankuendigungModal = (e) => {
        bfsgModal = false;
        vorankuendigungModal = true;
    }

    const toggle = () => {
        opened = !opened;
    }
</script>

<div class="card">
    <header class="card-header" on:click={toggle}>
        <p class="card-header-title">
            BFSG
        </p>
        <button class="card-header-icon" aria-label="more options">
            <AngleIndicator {opened}/>
        </button>
    </header>
    {#if opened}
        <div class="card-content">
            <div class="content">
                <h3 class="heading is-3">Vorankündigungen</h3>
                {#if $loggedInUser && $loggedInUser.admin}
                    <button class="button is-outlined is-small" on:click|stopPropagation={showVorankuendigungModal}>
                        Antrag stellen
                    </button>
                {/if}
                {#if vorankuendigungPayoutRequests}
                    <PayoutRequestsTable singleFS="{true}" bfsgPayoutRequests="{vorankuendigungPayoutRequests}"
                                         {budgetTitlesBfsg} type="vorankuendigung"/>
                {:else}
                    <p class="has-text-grey-dark">Keine vorhanden.</p>
                {/if}

                <h3 class="heading is-3">BFSG-Anträge</h3>
                {#if $loggedInUser && $loggedInUser.admin}
                    <button class="button is-outlined is-small" on:click|stopPropagation={showBfsgModal}>
                        Antrag stellen
                    </button>
                {/if}
                {#if bfsgPayoutRequests}
                    <PayoutRequestsTable singleFS="{true}" {bfsgPayoutRequests} {budgetTitlesBfsg} type="bfsg"/>
                {:else}
                    <p class="has-text-grey-dark">Keine vorhanden.</p>
                {/if}
            </div>
        </div>
    {/if}
</div>

{#if bfsgModal}
    <BfsgRequestModal fsName="{studentBody.name}" fsId="{studentBody.id}" bind:modal={bfsgModal}/>
{/if}

{#if vorankuendigungModal}
    <VorankuendigungRequestModal fsName="{studentBody.name}" fsId="{studentBody.id}" bind:modal={vorankuendigungModal}/>
{/if}

<style>
    .card-header {
        cursor: pointer;
    }
</style>

// src/components/studentbody/BfsgSection.vue
<script setup lang="ts">
import type {IStudentBody} from "@/interfaces";
import {computed, ref} from "vue";
import AngleIndicator from "@/components/icons/AngleIndicator.vue";
import {useAccountStore} from "@/stores/account";
import PayoutRequestsTable from "@/components/payoutrequest/PayoutRequestsTable.vue";
import {usePayoutRequestStore} from "@/stores/payoutRequest";
import BfsgRequestModal from "@/components/payoutrequest/BfsgRequestModal.vue";
import VorankuendigungRequestModal from "@/components/payoutrequest/VorankuendigungRequestModal.vue";

const props = defineProps<{
  studentBody: IStudentBody,
}>()

const account = useAccountStore();
const payoutRequests = usePayoutRequestStore();

const opened = ref(false);
const bfsgModal = ref(false);
const vorankuendigungModal = ref(false);

const showBfsgModal = () => {
  bfsgModal.value = true;
  vorankuendigungModal.value = false;
}

const showVorankuendigungModal = () => {
  bfsgModal.value = false;
  vorankuendigungModal.value = true;
}

const toggle = () => {
  opened.value = !opened.value;
}

const vorankuendigungPayoutRequests = computed(() => payoutRequests.vorankuendigung?.get(props.studentBody.id))
const bfsgPayoutRequests = computed(() => payoutRequests.bfsg?.get(props.studentBody.id))

</script>

<template>
  <div class="card">
    <header class="card-header" @click="toggle">
      <p class="card-header-title">
        BFSG
      </p>
      <button class="card-header-icon" aria-label="more options">
        <AngleIndicator :opened="opened"/>
      </button>
    </header>
    <div v-if="opened" class="card-content">
      <div class="content">
        <h3 class="heading is-3">Vorankündigungen</h3>
        <button v-if="account.user?.admin" class="button is-outlined is-small" @click.stop="showVorankuendigungModal">
          Antrag stellen
        </button>
        <PayoutRequestsTable v-if="vorankuendigungPayoutRequests" :singleFS="true"
                             :bfsgPayoutRequests="vorankuendigungPayoutRequests"
                             type="vorankuendigung"/>
        <p v-else class="has-text-grey-dark">Keine vorhanden.</p>

        <h3 class="heading is-3">BFSG-Anträge</h3>
        <button v-if="account.user?.admin" class="button is-outlined is-small" @click.stop="showBfsgModal">
          Antrag stellen
        </button>
        <PayoutRequestsTable v-if="bfsgPayoutRequests" :singleFS="true" :bfsgPayoutRequests="bfsgPayoutRequests"
                             type="bfsg"/>
        <p v-else class="has-text-grey-dark">Keine vorhanden.</p>
      </div>
    </div>
  </div>

    <BfsgRequestModal v-if="bfsgModal" :fsName="studentBody.name" :fsId="studentBody.id" v-model="bfsgModal"/>
    <VorankuendigungRequestModal v-if="vorankuendigungModal" :fsName="studentBody.name" :fsId="studentBody.id"
                                 v-model="vorankuendigungModal"/>
</template>

<style scoped>
.card-header {
  cursor: pointer;
}
</style>
