// src/components/PayoutRequestsTable.svelte
<script type="ts">
    import type {INewPayoutRequestData} from "../Interfaces";
    import PayoutRequestRow from "./PayoutRequestRow.svelte";

    export let bfsgPayoutRequests: INewPayoutRequestData[]
    export let singleFS: boolean = false;
    export let type: string;
    export let budgetTitlesBfsg: { [semester: string]: string } = {};
</script>

<table class="table is-narrow">
    <thead>
    <tr>
        <th>Antragsnummer</th>
        {#if !singleFS}
            <th>Fachschaft</th>
        {/if}
        <th>Referenz</th>
        <th>Kategorie</th>
        <th>Semester</th>
        <th>Betrag</th>
        <th>Status</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {#each bfsgPayoutRequests as payoutRequest (payoutRequest.request_id)}
        <PayoutRequestRow {singleFS} {payoutRequest} {type} {budgetTitlesBfsg}/>
    {/each}
    </tbody>
</table>

// src/components/payoutrequest/PayoutRequestsTable.vue
<script setup lang="ts">
import type {INewPayoutRequestData} from "@/interfaces";
import PayoutRequestRow from "@/components/payoutrequest/PayoutRequestRow.vue";

defineProps<{
  bfsgPayoutRequests: INewPayoutRequestData[],
  singleFS: boolean,
  type: string,
}>()

</script>

<template>
  <table class="table is-narrow">
    <thead>
    <tr>
      <th>Antragsnummer</th>
      <th v-if="!singleFS">Fachschaft</th>
      <th>Referenz</th>
      <th>Kategorie</th>
      <th>Semester</th>
      <th>Betrag</th>
      <th>Status</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <PayoutRequestRow v-for="payoutRequest in bfsgPayoutRequests" :key="payoutRequest.request_id"
                      :singleFS="singleFS" :payoutRequest="payoutRequest" :type="type"/>
    </tbody>
  </table>
</template>

<style scoped>

</style>
