// src/components/diff/DocumentDiff.vue
<script setup lang="ts">
import type {IAnnotatedDocument} from "@/interfaces";
import {computed} from "vue";

const props = defineProps<{
  before: IAnnotatedDocument | null | undefined,
  after: IAnnotatedDocument | null | undefined,
}>();

const jsonRepresentationIsDifferent = (first: any, second: any) => {
  return JSON.stringify(first) !== JSON.stringify(second);
}

const checkedChanged = computed(() => props.before?.checked !== props.after?.checked);
const referencesChanged = computed(() => props.before?.references.join(',') !== props.after?.references.join(','));
const annotationsChanged = computed(() => jsonRepresentationIsDifferent(props.before?.annotations, props.after?.annotations));
const referenceAnnotationsChanged = computed(() => !referencesChanged.value && jsonRepresentationIsDifferent(props.before?.resolvedReferences, props.after?.resolvedReferences));
</script>

<template>
  <td>
    <template v-if="before">
      <code>{{ before.filename }}</code>
      <ul>
        <li v-if="checkedChanged">geprüft: {{ before.checked ? 'Ja' : 'Nein' }}</li>
        <li v-if="referencesChanged">Referenzen:
          <ul>
            <template v-if="before.references.length">
              <li v-for="reference in before.references" :key="reference">
                <code>{{ reference }}</code>
              </li>
            </template>
            <li v-else>–</li>
          </ul>
        </li>
        <li v-if="annotationsChanged">Anmerkungen:
          <ul>
            <template v-if="before.annotations.length">
              <li v-for="annotation in before.annotations" :key="annotation.text">
                {{ annotation.level }}: {{annotation.text}}
              </li>
            </template>
            <li v-else>–</li>
          </ul>
        </li>
        <li v-if="before.references.length > 0 && referenceAnnotationsChanged">
        <span class="has-text-grey has-background-grey-lighter">
          Anmerkungen von Referenzen wurden modifiziert
        </span>
        </li>
      </ul>
    </template>
    <span v-else class="has-text-grey has-background-grey-lighter">(wurde neu erstellt)</span>
  </td>
  <td>
    <template v-if="after">
      <code>{{ after.filename }}</code>
      <ul>
        <li v-if="checkedChanged">geprüft: {{ after.checked ? 'Ja' : 'Nein' }}</li>
        <li v-if="referencesChanged">Referenzen:
          <ul>
            <template v-if="after.references.length">
              <li v-for="reference in after.references" :key="reference">
                <code>{{ reference }}</code>
              </li>
            </template>
            <li v-else>–</li>
          </ul>
        </li>
        <li v-if="annotationsChanged">Anmerkungen:
          <ul>
            <template v-if="after.annotations.length">
              <li v-for="annotation in after.annotations" :key="annotation.text">
                {{ annotation.level }}: {{annotation.text}}
              </li>
            </template>
            <li v-else>–</li>
          </ul>
        </li>
        <li v-if="after.references.length > 0 && referenceAnnotationsChanged">
        <span class="has-text-grey has-background-grey-lighter">
          Anmerkungen von Referenzen wurden modifiziert
        </span>
        </li>
      </ul>
    </template>
    <span v-else class="has-text-grey has-background-grey-lighter">(wurde neu erstellt)</span>
  </td>
</template>

<style scoped>
td {
  width: 42.5%;
}
</style>

// src/components/diff/DocumentDiff.svelte
<script type="ts">
    import type {IAnnotatedDocument} from "../../Interfaces";

    const jsonRepresentationIsDifferent = (first, second) => {
        return JSON.stringify(first) !== JSON.stringify(second);
    }

    export let before: IAnnotatedDocument | null | undefined;
    export let after: IAnnotatedDocument | null | undefined;
    let checkedChanged = true;
    let referencesChanged = true;
    let annotationsChanged = true;
    let referenceAnnotationsChanged = true;
    if (before && after) {
        checkedChanged = before.checked !== after.checked;
        referencesChanged = before.references.join(',') !== after.references.join(',');
        annotationsChanged = jsonRepresentationIsDifferent(before.annotations, after.annotations);
        referenceAnnotationsChanged = !referencesChanged && jsonRepresentationIsDifferent(before.resolvedReferences, after.resolvedReferences);
    }
</script>

<td>
    {#if before}
        <code>{before.filename}</code>
        <ul>
            {#if checkedChanged}
                <li>geprüft: {before.checked ? 'Ja' : 'Nein'}</li>
            {/if}
            {#if referencesChanged}
                <li>Referenzen:
                    <ul>
                        {#each before.references as reference}
                            <li><code>{reference}</code></li>
                        {:else}
                            <li>–</li>
                        {/each}
                    </ul>
                </li>
            {/if}
            {#if annotationsChanged}
                <li>Anmerkungen:
                    <ul>
                        {#each before.annotations as annotation}
                            <li>{annotation.level}: {annotation.text}</li>
                        {:else}
                            <li>–</li>
                        {/each}
                    </ul>
                </li>
            {/if}
            {#if before.references.length > 0 && referenceAnnotationsChanged}
                <li><span class="has-text-grey has-background-grey-lighter">
                    Anmerkungen von Referenzen wurden modifiziert
                </span></li>
            {/if}
        </ul>
    {:else }
        <span class="has-text-grey has-background-grey-lighter">(wurde neu erstellt)</span>
    {/if}
</td>
<td>
    {#if after}
        <code>{after.filename}</code>
        <ul>
            {#if checkedChanged}
                <li>geprüft: {after.checked ? 'Ja' : 'Nein'}</li>
            {/if}
            {#if referencesChanged}
                <li>Referenzen:
                    <ul>
                        {#each after.references as reference}
                            <li><code>{reference}</code></li>
                        {:else}
                            <li>–</li>
                        {/each}
                    </ul>
                </li>
            {/if}
            {#if annotationsChanged}
                <li>Anmerkungen:
                    <ul>
                        {#each after.annotations as annotation}
                            <li>{annotation.level}: {annotation.text}</li>
                        {:else}
                            <li>–</li>
                        {/each}
                    </ul>
                </li>
            {/if}
            {#if after.references.length > 0 && referenceAnnotationsChanged}
                <li><span class="has-text-grey has-background-grey-lighter">
                    Anmerkungen von Referenzen wurden modifiziert
                </span></li>
            {/if}
        </ul>
    {:else }
        <span class="has-text-grey has-background-grey-lighter">(wurde gelöscht/umbenannt)</span>
    {/if}
</td>

<style>
    td {
        width: 42.5%;
    }
</style>
