// src/components/diff/PayoutRequestDiff.svelte
<script type="ts">
    import {INewPayoutRequestData} from "../../Interfaces";
    import {euroCents} from "../../util";

    export let before: INewPayoutRequestData | null | undefined;
    export let after: INewPayoutRequestData | null | undefined;
    $: idClass = (before && after) && (before.request_id !== after.request_id) ? 'is-warning' : '';
    $: categoryClass = (before && after) && (before.category !== after.category) ? 'is-warning' : '';
    $: statusClass = (before && after) && (before.status !== after.status) ? 'is-warning' : '';
    $: amountClass = (before && after) && (before.amount_cents !== after.amount_cents) ? 'is-warning' : '';
    $: dateClass = (before && after) && (before.request_date !== after.request_date) ? 'is-warning' : '';
    $: deadlineClass = (before && after) && (before.completion_deadline !== after.completion_deadline) ? 'is-warning' : '';
    $: commentClass = (before && after) && (before.comment !== after.comment) ? 'is-warning' : '';
    $: referenceClass = (before && after) && (before.reference !== after.reference) ? 'is-warning' : '';
</script>

<td>
    {#if before}
        <ul>
            <li>ID: <span class="tag {idClass}">{before.request_id}</span></li>
            <li>Kategorie: <span class="tag {categoryClass}">{before.category}</span></li>
            <li>Status: <span class="tag {statusClass}">{before.status}</span></li>
            <li>Betrag: <span class="tag {amountClass}">{euroCents(before.amount_cents)}</span></li>
            <li>Antragsdatum: <span class="tag {dateClass}">{before.request_date}</span></li>
            <li>Deadline: <span class="tag {deadlineClass}">{before.completion_deadline}</span></li>
            <li>Kommentar: <span class="tag {commentClass}">{before.comment}</span></li>
            <li>Referenz: <span class="tag {referenceClass}">{before.reference}</span></li>
        </ul>
    {:else }
        -nix-
    {/if}
</td>
<td>
    {#if after}
        <ul>
            <li>ID: <span class="tag {idClass}">{after.request_id}</span></li>
            <li>Kategorie: <span class="tag {categoryClass}">{after.category}</span></li>
            <li>Status: <span class="tag {statusClass}">{after.status}</span></li>
            <li>Betrag: <span class="tag {amountClass}">{euroCents(after.amount_cents)}</span></li>
            <li>Antragsdatum: <span class="tag {dateClass}">{after.request_date}</span></li>
            <li>Deadline: <span class="tag {deadlineClass}">{after.completion_deadline}</span></li>
            <li>Kommentar: <span class="tag {commentClass}">{after.comment}</span></li>
            <li>Referenz: <span class="tag {referenceClass}">{after.reference}</span></li>
        </ul>
    {:else }
        -nix-
    {/if}
</td>

// src/components/diff/PayoutRequestDiff.vue
<script setup lang="ts">
import type {INewPayoutRequestData} from "@/interfaces";
import {euroCents} from "../../util";
import {computed} from "vue";

const props = defineProps<{
  before: INewPayoutRequestData | null | undefined,
  after: INewPayoutRequestData | null | undefined,
}>();

const idClass = computed(()=>(props.before?.request_id !== props.after?.request_id) ? 'tag is-warning' : 'tag');
const categoryClass = computed(()=>(props.before?.category !== props.after?.category) ? 'tag is-warning' : 'tag');
const statusClass = computed(()=>(props.before?.status !== props.after?.status) ? 'tag is-warning' : 'tag');
const amountClass = computed(()=>(props.before?.amount_cents !== props.after?.amount_cents) ? 'tag is-warning' : 'tag');
const dateClass = computed(()=>(props.before?.completion_deadline !== props.after?.completion_deadline) ? 'tag is-warning' : 'tag');
const deadlineClass = computed(()=>(props.before?.comment !== props.after?.comment) ? 'tag is-warning' : 'tag');
const commentClass = computed(()=>(props.before?.comment !== props.after?.comment) ? 'tag is-warning' : 'tag');
const referenceClass = computed(()=>(props.before?.reference !== props.after?.reference) ? 'tag is-warning' : 'tag');
</script>

<template>
  <td>
    <ul v-if="before">
      <li>ID: <span :class="idClass">{{before.request_id}}</span></li>
      <li>Kategorie: <span :class="categoryClass">{{before.category}}</span></li>
      <li>Status: <span :class="statusClass">{{before.status}}</span></li>
      <li>Betrag: <span :class="amountClass">{{euroCents(before.amount_cents)}}</span></li>
      <li>Antragsdatum: <span :class="dateClass">{{before.request_date}}</span></li>
      <li>Deadline: <span :class="deadlineClass">{{before.completion_deadline}}</span></li>
      <li>Kommentar: <span :class="commentClass">{{before.comment}}</span></li>
      <li>Referenz: <span :class="referenceClass">{{before.reference}}</span></li>
    </ul>
    <p v-else>-nix-</p>
  </td>
  <td>
    <ul v-if="after">
      <li>ID: <span :class="idClass">{{after.request_id}}</span></li>
      <li>Kategorie: <span :class="categoryClass">{{after.category}}</span></li>
      <li>Status: <span :class="statusClass">{{after.status}}</span></li>
      <li>Betrag: <span :class="amountClass">{{euroCents(after.amount_cents)}}</span></li>
      <li>Antragsdatum: <span :class="dateClass">{{after.request_date}}</span></li>
      <li>Deadline: <span :class="deadlineClass">{{after.completion_deadline}}</span></li>
      <li>Kommentar: <span :class="commentClass">{{after.comment}}</span></li>
      <li>Referenz: <span :class="referenceClass">{{after.reference}}</span></li>
    </ul>
    <p v-else>-nix-</p>
  </td>
</template>

<style scoped>

</style>
