// src/components/CopyableTag.vue
<script setup lang="ts">
import {copyToClipboard} from "@/util";
import {type Ref, ref} from "vue";

const props = withDefaults(defineProps<{
  text: string,
  copyText: string | undefined,
  bold: boolean,
  tagClass: string,
}>(), {copyText: undefined, bold: false, tagClass: 'is-light'})

const textOverride: Ref<string | null> = ref(null);
const clickCallback = () => {
  copyToClipboard(props.copyText || props.text);
  textOverride.value = 'kopiert!';
  setTimeout(() => {
    textOverride.value = null;
  }, 1000);
}
</script>

<template>
  <span :class="'tag ' + tagClass + (bold ? ' has-text-weight-bold' : '')" @click.stop="clickCallback">
    <Transition mode="out-in">
      <span v-if="textOverride">
        {{ textOverride }}
      </span>
      <span v-else>
        {{ text }}
      </span>
    </Transition>
  </span>
</template>

<style scoped>
.tag {
  margin-bottom: 0;
  cursor: pointer;
}

.is-strikethrough {
  text-decoration: line-through;
}

.v-enter-active,
.v-leave-active {
  transition: opacity 0.1s ease;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}
</style>

// src/components/CopyableTag.svelte
<script type="ts">
    import {fade} from 'svelte/transition';
    import {copyToClipboard} from "../util";

    const clickCallback = () => {
        copyToClipboard(copyText || text);
        const oldText = text;
        text = 'kopiert!';
        setTimeout(() => {
            text = oldText;
        }, 1000);
    }

    export let text = '';
    export let copyText = undefined;
    export let bold = false;
    export let tagClass = 'is-light';
</script>

<span class="tag {tagClass}" on:click|stopPropagation={clickCallback}>
{#key text}
    <span in:fade>
{#if bold}<b>{text}</b>{:else}{text}{/if}
    </span>
{/key}
</span>


<style>
    .tag {
        margin-bottom: 0;
        cursor: pointer;
    }
    .is-strikethrough {
        text-decoration: line-through;
    }
</style>
