// src/components/DateRange.vue
<script setup lang="ts">
import type {Interval} from "@/Calculator";
import {formatDate} from "@/util";

defineProps<{
  interval: Interval,
}>()
</script>

<template>
  <template v-if="interval.start.toUTCString() === interval.end.toUTCString()">
    {{ formatDate(interval.start) }}
  </template>
  <template v-else>
    {{ formatDate(interval.start) }} – {{ formatDate(interval.end) }}
  </template>
</template>

<style scoped>
</style>

// src/components/DateRange.svelte
<script type="ts">
    import {Interval} from "../Calculator";
    import {formatDate} from "../util";

    export let interval: Interval;
</script>

{#if interval.start.toUTCString() === interval.end.toUTCString()}
    {formatDate(interval.start)}
{:else}
    {formatDate(interval.start)} – {formatDate(interval.end)}
{/if}
