// src/components/document/SingleDocumentWithoutReferences.vue
<script setup lang="ts">
import type {IAnnotatedDocument, IStudentBody} from "@/interfaces";
import SingleDocument from "@/components/document/SingleDocument.vue";

defineProps<{
  document: IAnnotatedDocument,
  studentBody: IStudentBody,
}>()
</script>

<template>
  <SingleDocument :document="document" :studentBody="studentBody" :withReferences="false"/>
</template>

<style scoped>
</style>

// src/components/SingleDocumentWithoutReferences.svelte
<script type="ts">
    import type {IAnnotatedDocument, IStudentBody} from "../Interfaces";
    import SingleDocument from "./SingleDocument.svelte";

    export let document: IAnnotatedDocument;
    export let studentBody: IStudentBody;
</script>

<SingleDocument {document} {studentBody} withReferences={false}/>
