// src/components/document/DocumentsList.vue
<script setup lang="ts">

import type {IStudentBody} from "@/interfaces";
import SingleDocument from "@/components/document/SingleDocument.vue";

defineProps<{
  studentBody: IStudentBody,
}>()
</script>

<template>
  <div class="card-content">
    <div class="content">
      <h3 class="heading is-3">Haushaltspläne</h3>
      <template v-if="studentBody.budgets.length > 0">
        <ul>
          <li v-for="budget in studentBody.budgets" :key="budget.filename">
            <SingleDocument :document="budget" :studentBody="studentBody"/>
          </li>
        </ul>
      </template>
      <template v-else>
        Keine vorhanden.
      </template>
      <h3 class="heading is-3">Haushaltsrechnungen</h3>
      <template v-if="studentBody.balances.length > 0">
        <ul>
          <li v-for="balance in studentBody.balances" :key="balance.filename">
            <SingleDocument :document="balance" :studentBody="studentBody"/>
          </li>
        </ul>
      </template>
      <template v-else>
        Keine vorhanden.
      </template>
      <h3 class="heading is-3">Kassenprüfungen</h3>
      <template v-if="studentBody.cashAudits.length > 0">
        <ul>
          <li v-for="cashAudit in studentBody.cashAudits" :key="cashAudit.filename">
            <SingleDocument :document="cashAudit" :studentBody="studentBody"/>
          </li>
        </ul>
      </template>
      <template v-else>
        Keine vorhanden.
      </template>
      <h3 class="heading is-3">Protokolle</h3>
      <template v-if="studentBody.proceedings.length > 0">
        <ul>
          <li v-for="proceeding in studentBody.proceedings" :key="proceeding.filename">
            <SingleDocument :document="proceeding" :studentBody="studentBody"/>
          </li>
        </ul>
      </template>
      <template v-else>
        Keine vorhanden.
      </template>
      <h3 class="heading is-3">Wahlergebnisse</h3>
      <template v-if="studentBody.electionResults.length > 0">
        <ul>
          <li v-for="electionResult in studentBody.electionResults" :key="electionResult.filename">
            <SingleDocument :document="electionResult" :studentBody="studentBody"/>
          </li>
        </ul>
      </template>
      <template v-else>
        Keine vorhanden.
      </template>
    </div>
  </div>
</template>

<style scoped>
li {
  list-style: none;
}
</style>

// src/sections/DocumentsList.svelte
<script type="ts">
    import type {IStudentBody} from "../Interfaces";
    import SingleDocument from "../components/SingleDocument.svelte";

    export let studentBody: IStudentBody;
</script>


<div class="card-content">
    <div class="content">
        <h3 class="heading is-3">Haushaltspläne</h3>
        <ul>
            {#each studentBody.budgets as budget}
                <li><SingleDocument document="{budget}" {studentBody}/></li>
            {:else}
                Keine vorhanden.
            {/each}
        </ul>
        <h3 class="heading is-3">Haushaltsrechnungen</h3>
        <ul>
            {#each studentBody.balances as balance}
                <li><SingleDocument document="{balance}" {studentBody}/></li>
            {:else}
                Keine vorhanden.
            {/each}
        </ul>
        <h3 class="heading is-3">Kassenprüfungen</h3>
        <ul>
            {#each studentBody.cashAudits as cashAudit}
                <li><SingleDocument document="{cashAudit}" {studentBody}/></li>
            {:else}
                Keine vorhanden.
            {/each}
        </ul>
        <h3 class="heading is-3">Protokolle</h3>
        <ul>
            {#each studentBody.proceedings as proceeding}
                <li><SingleDocument document="{proceeding}" {studentBody}/></li>
            {:else}
                <li>Keine vorhanden.</li>
            {/each}
        </ul>
        <h3 class="heading is-3">Wahlergebnisse</h3>
        <ul>
            {#each studentBody.electionResults as electionResult}
                <li><SingleDocument document="{electionResult}" {studentBody}/></li>
            {:else}
                <li>Keine vorhanden.</li>
            {/each}
        </ul>
    </div>
</div>

<style>
    li {
        list-style: none;
    }
</style>
