// src/components/studentbody/DocumentsSection.vue
<script setup lang="ts">

import AngleIndicator from "@/components/icons/AngleIndicator.vue";
import {ref} from "vue";
import type {IStudentBody} from "@/interfaces";
import DocumentsList from "@/components/document/DocumentsList.vue";

defineProps<{
  studentBody: IStudentBody,
}>()

const opened = ref(false);
const toggle = () => {
  opened.value = !opened.value;
}
</script>

<template>
  <div class="card">
    <header class="card-header" @click="toggle">
      <p class="card-header-title">
        Dokumente
      </p>
      <button class="card-header-icon" aria-label="more options">
        <AngleIndicator :opened="opened"/>
      </button>
    </header>
    <DocumentsList v-if="opened" :studentBody="studentBody"/>
  </div>
</template>

<style scoped>
.card-header {
  cursor: pointer;
}
</style>

// src/sections/DocumentsSection.svelte
<script type="ts">
    import type {IStudentBody} from "../Interfaces";
    import AngleIndicator from "../icons/AngleIndicator.svelte";
    import DocumentsList from "./DocumentsList.svelte";

    export let studentBody: IStudentBody;
    let opened: boolean = false;

    const toggle = () => {
        opened = !opened;
    }
</script>

<div class="card">
    <header class="card-header" on:click={toggle}>
        <p class="card-header-title">
            Dokumente
        </p>
        <button class="card-header-icon" aria-label="more options">
            <AngleIndicator {opened}/>
        </button>
    </header>
    {#if opened}
        <DocumentsList {studentBody}/>
    {/if}
</div>

<style>
    .card-header {
        cursor: pointer;
    }
</style>
