// src/components/studentbody/SemesterSection.vue
<script setup lang="ts">

import {usePageSettingsStore} from "@/stores/pageSettings";
import {computed, ref} from "vue";
import type {IStudentBody} from "@/interfaces";
import {type Interval, SemesterCalculator} from "@/Calculator";
import {calculateSemesterId, calculateSemesterName, shouldDisplayStar} from "@/util";
import {usePayoutRequestStore} from "@/stores/payoutRequest";
import IconForLevel from "@/components/icons/IconForLevel.vue";
import DateRange from "@/components/DateRange.vue";
import DeadlineIcons from "@/components/icons/DeadlineIcons.vue";
import IconStar from "@/components/icons/IconStar.vue";
import AngleIndicator from "@/components/icons/AngleIndicator.vue";
import SemesterContent from "@/components/studentbody/SemesterContent.vue";

const props = defineProps<{
  studentBody: IStudentBody,
  semester: Interval
}>()

const settings = usePageSettingsStore();
const payoutRequests = usePayoutRequestStore();

const opened = ref(false);

const calculateLevel = (studentBody: IStudentBody, semester: Interval) => {
  const calculator = new SemesterCalculator(studentBody, semester);
  return calculator.calculateOverallLevel();
}

const toggle = () => {
  opened.value = !opened.value;
}
const semesterName = computed(() => calculateSemesterName(props.semester))
const semesterId = computed(() => calculateSemesterId(props.semester))
const payoutRequestForSemester = computed(() => payoutRequests.afsg?.get(props.studentBody.id)?.find(value => value.semester === semesterId.value))
const level = computed(() => calculateLevel(props.studentBody, props.semester))
const displayStar = computed(() => shouldDisplayStar(level.value, payoutRequestForSemester.value))
</script>

<template>
  <template v-if="(!settings.showOnlySemestersWithPayoutRequests && !settings.showOnlySemestersWithStar)
|| (displayStar)
|| (!settings.showOnlySemestersWithStar && settings.showOnlySemestersWithPayoutRequests && payoutRequestForSemester)">
    <div class="card">
      <header class="card-header" @click="toggle">
        <p class="card-header-title">
          <IconForLevel :level="level"/>
            {{semesterName}}
            (
            <DateRange :interval="semester"/>)
              <DeadlineIcons :interval="semester"/>
        </p>
        <IconStar v-if="displayStar"/>
<!--        TODO -->
<!--          <PayoutRequest {payoutRequest} :fsName="studentBody.name" :fsId="studentBody.id" :budgetTitle="budgetTitle" :semester="semester"/>-->
          <button class="card-header-icon" aria-label="more options">
            <AngleIndicator :opened="opened"/>
          </button>
      </header>
      <SemesterContent v-if="opened" :studentBody="studentBody" :semester="semester"/>
    </div>
  </template>
</template>

<style scoped>
.card-header {
  cursor: pointer;
}

</style>

// src/sections/SemesterSection.svelte
<script type="ts">
    import type {IStudentBody} from "../Interfaces";
    import CurrentlyCanBePaidContent from "./CurrentlyCanBePaidContent.svelte";
    import AngleIndicator from "../icons/AngleIndicator.svelte";
    import DocumentsList from "./DocumentsList.svelte";
    import {Interval, SemesterCalculator} from "../Calculator";
    import DateRange from "../components/DateRange.svelte";
    import SemesterContent from "./SemesterContent.svelte";
    import IconForLevel from "../icons/IconForLevel.svelte";
    import {INewPayoutRequestData, IPayoutRequestData} from "../Interfaces";
    import PayoutRequest from "../components/PayoutRequest.svelte";
    import AttentionStar from "../components/AttentionStar.svelte";
    import {showOnlySemestersWithPayoutRequests, showOnlySemestersWithStar} from "../stores";
    import {calculateSemesterId, calculateSemesterName, shouldDisplayStar} from "../util";
    import DeadlineIcon from "../components/DeadlineIcon.svelte";

    const calculateLevel = (studentBody: IStudentBody, semester: Interval) => {
        const calculator = new SemesterCalculator(studentBody, semester);
        return calculator.calculateOverallLevel();
    }


    export let studentBody: IStudentBody;
    export let budgetTitles: { [semester: string]: string };
    export let semester: Interval;
    $: level = calculateLevel(studentBody, semester);
    $: semesterName = calculateSemesterName(semester);
    $: semesterId = calculateSemesterId(semester);
    export let payoutRequests: Map<string, INewPayoutRequestData> | undefined;
    $: payoutRequest = payoutRequests ? payoutRequests.get(semesterId) : null;
    $: budgetTitle = budgetTitles ? budgetTitles[semesterId] : '';
    $: displayStar = shouldDisplayStar(level, payoutRequest);
    let opened: boolean = false;

    const toggle = () => {
        opened = !opened;
    }
</script>

{#if (!$showOnlySemestersWithPayoutRequests && !$showOnlySemestersWithStar)
|| (displayStar)
|| (!$showOnlySemestersWithStar && $showOnlySemestersWithPayoutRequests && payoutRequest)}
<div class="card">
    <header class="card-header" on:click={toggle}>
        <p class="card-header-title">
            <IconForLevel level={level}/>
            {semesterName}
            (<DateRange interval={semester}/>)
            <DeadlineIcon  interval={semester}/>
        </p>
        <AttentionStar display={displayStar}/>
        <PayoutRequest {payoutRequest} fsName={studentBody.name} fsId={studentBody.id} {budgetTitle} {semester}/>
        <button class="card-header-icon" aria-label="more options">
            <AngleIndicator {opened}/>
        </button>
    </header>
    {#if opened}
        <SemesterContent {studentBody} {semester}/>
    {/if}
</div>
{/if}

<style>
    .card-header {
        cursor: pointer;
    }
</style>
