// src/App.vue
<script setup lang="ts">
import {RouterView} from 'vue-router'
import NavbarView from "@/views/NavbarView.vue";
import FooterView from "@/views/FooterView.vue";
import {useTokenStore} from "@/stores/token";
import {getAllFsData, getPayoutRequestData, loadLoggedInUser, pojoToIData} from "@/util";
import {useAccountStore} from "@/stores/account";
import {useAllFsData} from "@/stores/allFsData";
import {usePayoutRequestStore} from "@/stores/payoutRequest";
import {onBeforeMount, type Ref, ref} from "vue";
import type {IData} from "@/interfaces";
import {useScieboDataStore} from "@/stores/scieboData";
import {useStudentBodiesStore} from "@/stores/studentBodies";
import ErrorList from "@/components/ErrorList.vue";


const token = useTokenStore();
const account = useAccountStore();
const allFsData = useAllFsData();
const payoutRequests = usePayoutRequestStore();
const sciebo = useScieboDataStore();
const studentBodies = useStudentBodiesStore();


const fetchDataError: Ref<null | string> = ref(null);
const afsgPayoutRequestsDataError: Ref<null | string> = ref(null);
const bfsgPayoutRequestsDataError: Ref<null | string> = ref(null);
const vorankuendigungPayoutRequestsDataError: Ref<null | string> = ref(null);
const errors: Ref<string[]> = ref([]);

const loadData = () => {
  const fixedDate = null;
  const url = fixedDate ? `/data/history/${fixedDate}-data.json` : "/data/data.json";
  fetch(url)
      .then(response => response.json(), () => {
        fetchDataError.value = "Fetching data failed";
      })
      .then(rawdata => {
        try {
          const data: IData = pojoToIData(rawdata);

          sciebo.data = data;
          fetchDataError.value = null;
          studentBodies.studentBodies = [...data.studentBodies.keys()].sort();
        } catch (err: any) {
          fetchDataError.value = err.message;
        }
      }, reason => {
        fetchDataError.value = reason;
      });
};


const loadPayoutRequestData = () => {
  getPayoutRequestData('afsg', null)
      .then(data => {
        payoutRequests.afsg = data;
        afsgPayoutRequestsDataError.value = null;
      }, reason => {
        afsgPayoutRequestsDataError.value = reason;
      });
  getPayoutRequestData('bfsg', null)
      .then(data => {
        payoutRequests.bfsg = data;
        bfsgPayoutRequestsDataError.value = null;
      }, reason => {
        bfsgPayoutRequestsDataError.value = reason;
      });
  getPayoutRequestData('vorankuendigung', null)
      .then(data => {
        payoutRequests.vorankuendigung = data;
        vorankuendigungPayoutRequestsDataError.value = null;
      }, reason => {
        vorankuendigungPayoutRequestsDataError.value = reason;
      });
};

const loadError = () => {
  fetch("/data/error.json")
      .then(response => response.json(), () => {
        errors.value = [];
      })
      .then(value => {
        errors.value = value;
      });
};

const loadAllFsData = () => {
  getAllFsData(token.apiToken).then(data => allFsData.set(data));
};

const loadUser = () => {
  loadLoggedInUser(token.apiToken).then(user => account.login(user));
};


onBeforeMount(() => {
  loadUser();
  loadError();
  loadData();
  loadPayoutRequestData();
  loadAllFsData();
});

</script>

<template>
  <section class="main-content columns is-fullheight">
    <aside class="column is-2 is-narrow-mobile is-fullheight section is-hidden-mobile has-background-white-bis">
      <NavbarView/>
    </aside>

    <div class="container column is-10">
      <ErrorList v-if="errors.length" :errors="errors"/>
      <pre v-if="fetchDataError">{{fetchDataError}}</pre>
      <pre v-if="afsgPayoutRequestsDataError">{{afsgPayoutRequestsDataError}}</pre>
      <pre v-if="bfsgPayoutRequestsDataError">{{bfsgPayoutRequestsDataError}}</pre>
      <pre v-if="vorankuendigungPayoutRequestsDataError">{{vorankuendigungPayoutRequestsDataError}}</pre>
      <RouterView/>
    </div>
  </section>

  <footer class="footer">
    <FooterView/>
  </footer>
</template>

<style scoped>
</style>

// src/App.svelte
<script lang="ts">
    import type {IData} from "./Interfaces";
    import ErrorList from "./components/ErrorList.svelte";
    import {onDestroy, onMount} from "svelte";
    import {backendPrefix, refreshIntervalMilliseconds, siteTitle} from "./settings";
    import {
        afsgPayoutRequestData,
        allFsData,
        bfsgPayoutRequestData,
        fsen,
        token,
        vorankuendigungPayoutRequestData
    } from "./stores";
    import UserMenu from "./sections/UserMenu.svelte";
    import {getAllFsData, getBfsgPayoutRequestData, getPayoutRequestData, getUrlParameter, pojoToIData} from "./util";
    import DiffView from "./sections/DiffView.svelte";
    import MainView from "./components/MainView.svelte";


    const loadData = () => {
        const url = fixedDate ? `/data/history/${fixedDate}-data.json` : "/data/data.json";
        fetch(url)
            .then(response => response.json(), () => {
                fetchDataError = "Fetching data failed";
            })
            .then(rawdata => {
                try {
                    const data: IData = pojoToIData(rawdata);

                    fetchedData = data;
                    fetchDataError = null;
                    $fsen = [...data.studentBodies.keys()].sort();
                } catch (err) {
                    fetchDataError = err.message;
                }
            }, reason => {
                fetchDataError = reason;
            });
    };

    const loadPayoutRequestData = () => {
      getPayoutRequestData('afsg', fixedDate)
        .then(data => {
          $afsgPayoutRequestData = data;
          afsgPayoutRequestsDataError = null;
        }, reason => {
          afsgPayoutRequestsDataError = reason;
        });
      getBfsgPayoutRequestData('bfsg', fixedDate)
        .then(data => {
          $bfsgPayoutRequestData = data;
          bfsgPayoutRequestsDataError = null;
        }, reason => {
          bfsgPayoutRequestsDataError = reason;
        });
      getBfsgPayoutRequestData('vorankuendigung', fixedDate)
            .then(data => {
              $vorankuendigungPayoutRequestData = data;
              vorankuendigungPayoutRequestsDataError = null;
            }, reason => {
              vorankuendigungPayoutRequestsDataError = reason;
            });
    };

    const loadError = () => {
        fetch("/data/error.json")
            .then(response => response.json(), () => {
                errors = [];
            })
            .then(value => {
                errors = value;
            });
    };


    const loadAllFsData = () => {
        getAllFsData($token).then(data => $allFsData = data);
    };


    let fetchedData: IData | null = null;
    let fetchDataError: string | null = null;
    let afsgPayoutRequestsDataError: string | null = null;
    let bfsgPayoutRequestsDataError: string | null = null;
    let vorankuendigungPayoutRequestsDataError: string | null = null;
    let errors: string[] = [];
    let diffview = getUrlParameter('diff') !== null;
    const fixedDate = getUrlParameter('date');

    if (!diffview) {
        const interval = setInterval(async () => {
            loadError();
            loadData();
            loadPayoutRequestData();
        }, refreshIntervalMilliseconds);

        onMount(() => {
            loadError();
            loadData();
            loadPayoutRequestData();
            loadAllFsData();
        });

        onDestroy(() => clearInterval(interval));
    }
</script>

<svelte:head>
    <title>{siteTitle}</title>
</svelte:head>

<main>
    <UserMenu/>

    {#if errors.length > 0}
        <ErrorList {errors}/>
    {/if}

    {#if fetchDataError}
        <pre>{fetchDataError}</pre>
    {/if}

    {#if afsgPayoutRequestsDataError}
        <pre>{afsgPayoutRequestsDataError}</pre>
    {/if}
    {#if bfsgPayoutRequestsDataError}
        <pre>{bfsgPayoutRequestsDataError}</pre>
    {/if}
    {#if vorankuendigungPayoutRequestsDataError}
        <pre>{vorankuendigungPayoutRequestsDataError}</pre>
    {/if}

    {#if !diffview}
        <MainView {fixedDate} {fetchedData}/>
    {:else}
        <DiffView/>
    {/if}

</main>
<footer class="footer">
    <div class="content has-text-centered">
        <p>
            <strong>{siteTitle}</strong> ist freie Software.
            <a href="{backendPrefix}/docs">API-Dokumentation</a> ·
            <a href="https://github.com/FK-Bonn/fsen-records">Frontend</a> ·
            <a href="https://github.com/FK-Bonn/fsen-records-backend">Backend</a>
        </p>
    </div>
</footer>
