// src/components/FsDataHistoryModal.svelte
<script type="ts">
    import {getFsDataHistory} from "../util";
    import {token} from "../stores";
    import type {IFsData} from "../Interfaces";
    import {onMount} from "svelte";
    import FsDataHistoryEntry from "./FsDataHistoryEntry.svelte";

    export let fsDataHistoryModal: boolean = true;
    export let fs: string;
    let completedRequest: IFsData[] | null = null;
    let message = '';


    const close = (e) => {
        fsDataHistoryModal = false;
    }


    const loadHistory = () => {
        getFsDataHistory(fs, $token)
            .then(data => {
                completedRequest = data;
            });
    }

    onMount(() => {
        loadHistory();
    })
</script>
<div class="modal is-active" on:click|stopPropagation>
    <div class="modal-background"></div>
    <div class="modal-content">
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">
                    Daten für {fs}: Bearbeitungsverlauf
                </p>
            </header>
            <div class="card-content">
                <div class="content">
                    {#if message}
                        <article class="message">
                            <div class="message-body">
                                {message}
                            </div>
                        </article>
                    {:else if completedRequest}
                        {#each completedRequest as data, i}
                            <FsDataHistoryEntry {fs} {data}
                                                previous="{i===(completedRequest.length-1)?null:completedRequest[i+1]}"
                                                bind:fsDataHistoryModal={fsDataHistoryModal}/>
                            <hr>
                        {/each}
                    {:else}
                        Daten werden geladen…
                    {/if}
                </div>
            </div>
            <footer class="card-footer">
                <button class="button card-footer-item" on:click|stopPropagation={close}>Schließen</button>
            </footer>
        </div>
    </div>
    <button class="modal-close is-large" aria-label="close" on:click|stopPropagation={close}></button>
</div>

// src/components/fsdata/FsDataHistoryModal.vue
<script setup lang="ts">
import {onBeforeMount, type Ref, ref} from "vue";
import type {IFsData} from "@/interfaces";
import {getFsDataHistory} from "@/util";
import {useTokenStore} from "@/stores/token";
import FsDataHistoryEntry from "@/components/fsdata/FsDataHistoryEntry.vue";

const show = defineModel<boolean>({required: true});
const props = defineProps<{
  fs: string,
}>();

const token = useTokenStore();

const completedRequest: Ref<IFsData[] | null> = ref(null);
const message: Ref<string | null> = ref(null);
const close = () => {
  show.value = false;
}
const loadHistory = () => {
  getFsDataHistory(props.fs, token.apiToken)
      .then(data => {
        completedRequest.value = data;
      });
}
onBeforeMount(() => loadHistory());
</script>

<template>
  <div class="modal is-active" @click.stop>
    <div class="modal-background"></div>
    <div class="modal-content">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">
            Daten für {{fs}}: Bearbeitungsverlauf
          </p>
        </header>
        <div class="card-content">
          <div class="content">
            <article v-if="message" class="message">
              <div class="message-body">
                {message}
              </div>
            </article>
            <template v-else-if="completedRequest">
              <template v-for="(data, i) in completedRequest" :key="i">
                <FsDataHistoryEntry :fs="fs" :data="data"
                                    :previous="i===(completedRequest.length-1)?null:completedRequest[i+1]"
                                    v-model="show"/>
                <hr>
              </template>
            </template>
            <template v-else>
              Daten werden geladen…
            </template>
          </div>
        </div>
        <footer class="card-footer">
          <button class="button card-footer-item" @click.stop="close">Schließen</button>
        </footer>
      </div>
    </div>
    <button class="modal-close is-large" aria-label="close" @click.stop="close"></button>
  </div>
</template>

<style scoped>

</style>
